VERSION_MAJOR = 0
VERSION_MINOR = 1
VERSION_PATCH = 0
VERSION_SUFFIX = "-dev"

ASM := nasm
CC := gcc
LD := ld
OBJCOPY := objcopy
STRIP = strip
RM := rm -rf
MEMDISK := /usr/lib/syslinux/memdisk

LDFLAGS = -m elf_i386
CFLAGS  = -g -m32 -fno-builtin -fno-stack-protector -fomit-frame-pointer -fstrength-reduce -fno-pic -nostdinc
OBJCOPYFLAGS := -R .pdr -R .comment -R.note -S -O binary

IMAGE_NAME := fd.img
HDD_IMAGE ?= pros32-v.$(VERSION_STRING).img
GRUB_MOUNT ?= /mnt/disk