cmake_minimum_required(VERSION 3.31)
set(CMAKE_C_COMPILER_WORKS ON)
set(CMAKE_CXX_COMPILER_WORKS ON)
project(PRosBSD LANGUAGES C CXX ASM VERSION 0.2.1)

set(PROJECT_VERSION_SUFFIX "alpha.4")
set(PROJECT_TARGET_ARCH "i386")
set(PROJECT_VERSION_FULL "${PROJECT_VERSION}-${PROJECT_VERSION_SUFFIX}-${PROJECT_TARGET_ARCH}")
message(STATUS "${PROJECT_NAME} v.${PROJECT_VERSION_FULL}")

add_compile_definitions(PROSBSD_VERSION="${PROJECT_VERSION_FULL}")

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include_directories(${CMAKE_BINARY_DIR}/include)

add_subdirectory(kernel)
add_subdirectory(image)
