name: Build PRosBSD

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh -R
      - uses: actions/upload-artifact@v4
        with:
          name: PRosBSD
          path: "build/prosbsd.img"
